---
- name: Install Podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Enable and start Podman service
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: true
