---
- name: Import Microsoft GPG key
  ansible.builtin.rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  ansible.builtin.dnf_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    enabled: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install Visual Studio Code
  ansible.builtin.dnf:
    name: code
    state: present
