---
all:
  hosts:
    workstation1:
      ansible_host: #Add IP of host
    workstation2:
      ansible_host: #Add IP of host
  vars:
    ansible_user: #Add username
    ansible_ssh_private_key_file: #Add path to your private key
