---
- name: Import Microsoft GPG key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode respository
  yum_repostitory:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VSCode
  yum:
    name: code
    state: present
