---
- name: Add NodeSource repository GPG key
  ansible.builtin.get_url:
    url: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    dest: /etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
    mode: '0644'

- name: Add NodeSource repository
  ansible.builtin.dnf_repository:
    name: nodesource
    description: Node.js Packages for Enterprise Linux
    baseurl: https://rpm.nodesource.com/pub_14.x/el/$releasever/$basearch
    gpgkey: file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
    enabled: true
    gpgcheck: true

- name: Install Node.js
  ansible.builtin.dnf:
    name: nodejs
    state: present
