---
- name: Install Python 3
  ansible.builtin.dnf:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.command:
    cmd: python3 -m ensurepip
  args:
    creates: /usr/local/bin/pip3
