---
- name: Ensure all packages are up to date
  ansible.builtin.dnf:
    name: "*"
    state: present
  notify:
    - Reboot if needed

- name: Install basic packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - zsh
    - curl
    - wget
    - htop

- name: Ensure SELinux is installed
  ansible.builtin.dnf:
    name: libselinux
    state: present

- name: Ensure SELinux is enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is started and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open HTTP and HTTPS ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - http
    - https

- name: Open SSH port
  ansible.posix.firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Reload firewalld to apply changes
  ansible.posix.firewalld:
    state: reloaded
