---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible