---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.fedoraproject.org/fedora:latest
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
